AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda Ephemeral Storage Tester

Parameters:
  FileName:
    Description: The name of the file that function downloads from S3
    Type: String
    Default: 'data-file'
  StorageSize:
    Description: Size of the ephemeral storage
    Type: Number
    Default: 512

Resources:
  FileStorage:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-${AWS::Region}-${AWS::AccountId}-ephstorage'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 'development'
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          ThrottlingBurstLimit: '20'
          ThrottlingRateLimit: '40.0'

  ephemeralStorageTesterFunction:
   Type: AWS::Serverless::Function
   Properties:
     Handler: com.slalom.TempStorageCalculator
     Description: Function returning the size of the ephemeral storage after downloading an object from S3
     Runtime: java11
     CodeUri: build/distributions/lambdaEphemeral.zip
     Timeout: 900
     MemorySize: 10240
     Environment:
         Variables:
           S3_FILE_NAME: !Ref FileName
           S3_BUCKET_NAME: !Sub '${AWS::StackName}-${AWS::Region}-${AWS::AccountId}-ephstorage'
     Policies:
      - AWSXrayWriteOnlyAccess
      - AWSLambdaBasicExecutionRole
      - Statement:
        - Effect: "Allow" 
          Action: s3:GetObject
          Resource:
          - !Sub 'arn:aws:s3:::${AWS::StackName}-${AWS::Region}-${AWS::AccountId}-ephstorage/*'
        - Effect: "Allow" 
          Action: s3:ListBucket
          Resource:
          - !Sub 'arn:aws:s3:::${AWS::StackName}-${AWS::Region}-${AWS::AccountId}-ephstorage'
     Layers:
       - !Ref dependencyLibraries
     #Architectures:
     #  - arm64
     #EphemeralStorage:
     #   Size: !Ref StorageSize
     Tracing: Active
     Events:
       GetStorage:
         Type: Api
         Properties:
           Path: /ephemeral-storages
           Method: GET
           RestApiId:
             Ref: ApiGatewayApi

  dependencyLibraries:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: storage-tester-library
      Description: Dependencies for the functions
      Content: build/distributions/lambdaEphemeral-libs.zip
      CompatibleRuntimes:
        - java11
      #CompatibleArchitectures:
      #  - x86_64